### ISSUE TITLE
'gbk' codec can't encode character '\ufeff' 

### ISSUE THREAD

**Issue by yanning169** [HKUDS/LightRAG#1]
Traceback (most recent call last):
  File "E:\work\graphRAG\run.py", line 24, in <module>
    rag.insert(f.read())
  File "D:\Anaconda\envs\GraphRAG\Lib\site-packages\lightrag\lightrag.py", line 163, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\GraphRAG\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\GraphRAG\Lib\site-packages\lightrag\lightrag.py", line 225, in ainsert
    await self._insert_done()
  File "D:\Anaconda\envs\GraphRAG\Lib\site-packages\lightrag\lightrag.py", line 241, in _insert_done
    await asyncio.gather(*tasks)
  File "D:\Anaconda\envs\GraphRAG\Lib\site-packages\lightrag\storage.py", line 34, in index_done_callback
    write_json(self._data, self._file_name)
  File "D:\Anaconda\envs\GraphRAG\Lib\site-packages\lightrag\utils.py", line 102, in write_json
    json.dump(json_obj, f, indent=2, ensure_ascii=False)
  File "D:\Anaconda\envs\GraphRAG\Lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\ufeff' in position 70: illegal multibyte sequence

**Comment by LarFii** [comment]
Thanks for your attention! I have fix this issue in the latest code. You can reinstall this package.

**Comment by leezhuuuuu** [comment]
我今天在其他项目也发现这个问题，经过排查，是win编码与linux编码差异导致的问题
