### ISSUE TITLE
Could not automatically map gpt-4o-mini to a tokeniser

### ISSUE THREAD

**Issue by kofuya** [HKUDS/LightRAG#11]
Traceback (most recent call last):
  File "/model/rag_book.py", line 6, in <module>
    rag.insert(f.read())
  File "/usr/local/lib/python3.10/dist-packages/lightrag/lightrag.py", line 163, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/lightrag/lightrag.py", line 188, in ainsert
    for dp in chunking_by_token_size(
  File "/usr/local/lib/python3.10/dist-packages/lightrag/operate.py", line 31, in chunking_by_token_size
    tokens = encode_string_by_tiktoken(content, model_name=tiktoken_model)
  File "/usr/local/lib/python3.10/dist-packages/lightrag/utils.py", line 107, in encode_string_by_tiktoken
    ENCODER = tiktoken.encoding_for_model(model_name)
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-mini to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'

**Comment by adoresever** [comment]
https://youtu.be/02MqJgGvC2I?si=_DLbM7dq2oq-h-2A  I used gpt-40-mini

**Comment by LarFii** [comment]
Thank you for reporting this issue. It seems like the error is related to the tiktoken library; please check that your version is 0.7.0.

**Comment by bsyg** [comment]
I meet the same problem, when this issuse will be  fixed?

I use Qwen2.5:70B by ollama , but report this  error. Then, I replace all the "gpt-4o-mini" with "qwen2.5:70B" as the value of  variable  tiktoken_model_name. But this error is still reported.


Traceback (most recent call last):
  File "/home/LightRAG/examples/lightrag_ollama_demo.py", line 35, in <module>
    rag.insert(f.read())
  File "/root/anaconda3/lib/python3.11/site-packages/lightrag/lightrag.py", line 162, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/lightrag/lightrag.py", line 187, in ainsert
    for dp in chunking_by_token_size(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/lightrag/operate.py", line 32, in chunking_by_token_size
    tokens = encode_string_by_tiktoken(content, model_name=tiktoken_model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/lightrag/utils.py", line 121, in encode_string_by_tiktoken
    ENCODER = tiktoken.encoding_for_model(model_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/tiktoken/model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/lib/python3.11/site-packages/tiktoken/model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-mini to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
