### ISSUE TITLE
Run with ollama but failed when changing embedding models.

### ISSUE THREAD

**Issue by mokby** [HKUDS/LightRAG#118]
I am using lightrag with ollama, model is Qwen2, with the instruction in examples, and it works, but when I changed embeddings from `nomic-embed-text` into other embeddings, errors accured. I tried with three different embeddings which are `893379029/piccolo-large-zh-v2`, `herald/dmeta-embedding-zh` and `dmeta-embedding-zh`. I modify the embedding_dim but not help.

在使用ollama搭配Qwen2测试lightrag的时候,使用example中的例子是成功的，但是在我将embedding model更换为其他模型时却报错了，而且我使用了ollama的官方RAG实例测试这些embedding model结果都是成功的，说明embedding模型本身是没有问题的。

errors:
```
INFO:lightrag:Creating a new event loop in a sub-thread.
INFO:lightrag:[New Docs] inserting 1 docs
INFO:lightrag:[New Chunks] inserting 3 chunks
INFO:lightrag:Inserting 3 vectors to chunks
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/embeddings "HTTP/1.1 500 Internal Server Error"
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "/data/qrs/qwen_sharing/LightRAG/code/lightrag_qwen.py", line 25, in <module>
    rag.insert(f.read())
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/lightrag.py", line 162, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/lightrag.py", line 206, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/storage.py", line 92, in upsert
    embeddings_list = await asyncio.gather(
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/utils.py", line 87, in wait_func
    result = await func(*args, **kwargs)
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/utils.py", line 43, in __call__
    return await self.func(*args, **kwargs)
  File "/data/qrs/qwen_sharing/LightRAG/lightrag/llm.py", line 421, in ollama_embedding
    data = ollama.embeddings(model=embed_model, prompt=text)
  File "/usr/local/lib/python3.10/dist-packages/ollama/_client.py", line 281, in embeddings
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: failed to generate embedding
```

And I tried use offical ollama RAG method, these embedding models work just fine.
It would great if anybody could solve my problem.

**Comment by mokby** [comment]
It is so weird that I search every corn of the internet but still not solve this problem. But after many times tests, I found a embedding model that works, which called `mxbai-embed-large`, but other embedding models I want use still occur errors. Hope someone can help me.

**Comment by LarFii** [comment]
HTTP/1.1 500 Internal Server Error 可能属于网络通信问题，可以尝试将模型下载到本地使用

**Comment by mokby** [comment]
你好，我已经将模型下载到本地，不是网络问题，不过我在联系ollama的issue上找到了几个和我一样的问题，被证实是ollama本身的问题。

**Comment by LarFii** [comment]
问题已经解决了吗

**Comment by mokby** [comment]
> 问题已经解决了吗

并没有，目前只能使用特定的embedding

**Comment by mokby** [comment]
Can refer to this issue: https://github.com/ollama/ollama/issues/7288

**Comment by LarFii** [comment]
改小chunk size可能可以解决这个问题

**Comment by crux1981** [comment]
我用dmeta-embedding-zh做embedding时也遇到了这个问题，换用bge-base-zh-v1.5后通过了
