### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by Rainismer** [HKUDS/LightRAG#21]
from lightrag import LightRAG, QueryParam
from langchain_openai import ChatOpenAI
import os

WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

llm_4o_mini = ChatOpenAI(
    temperature=0,
    model_name="gpt-4o-mini",
    openai_api_key="......",
    openai_api_base="......",
)

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=llm_4o_mini
)

with open("./book.txt") as f:
    rag.insert(f.read())

# Perform naive search
print(rag.query("What are the top themes in this story?", param=QueryParam(mode="naive")))

# Perform local search
print(rag.query("What are the top themes in this story?", param=QueryParam(mode="local")))

# Perform global search
print(rag.query("What are the top themes in this story?", param=QueryParam(mode="global")))

# Perform hybrid search
print(rag.query("What are the top themes in this story?", param=QueryParam(mode="hybrid")))

-----------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "D:\AIGC\idataai_py\test\rag\light_rag.py", line 18, in <module>
    rag = LightRAG(
          ^^^^^^^^^
  File "<string>", line 25, in __init__
  File "D:\AIGC\idataai_py\venv\Lib\site-packages\lightrag\lightrag.py", line 106, in __post_init__
    _print_config = ",\n  ".join([f"{k} = {v}" for k, v in asdict(self).items()])
                                                           ^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1325, in _asdict_inner
    return copy.deepcopy(obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bozhum\AppData\Local\Programs\Python\Python311\Lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.RLock' object

**Comment by LarFii** [comment]
It seems that the issue might be related to the Python version. Could you try using Python 3.10 instead and see if it resolves the problem?

**Comment by Rainismer** [comment]
@LarFii My Python cannot be downgraded to 3.10. Additionally, I found that lightrag depends on hnswlib, which conflicts with chroma-hnswlib. I hope your new version can resolve these issues.

**Comment by Rainismer** [comment]
@LarFii 我们也可以用中文交流。

**Comment by LarFii** [comment]
好的，我后续会解决这些兼容性问题，解决后会第一时间通知你，请持续关注:)

**Comment by LarFii** [comment]
能给我一份你现有的package list吗，方便修复兼容性问题

**Comment by Rainismer** [comment]
@LarFii 好的！非常期待！333

**Comment by Rainismer** [comment]
@LarFii 
chromadb==0.4.24
crewai==0.70.1
crewai-tools==0.12.1
embedchain==0.1.122
fastapi==0.115.2
gitpython==3.1.43
langchain==0.2.16
langchainhub==0.1.21
langchain-chroma==0.1.4
langchain-openai==0.1.25
litellm==1.49.4
loguru==0.7.2
mysql-connector==2.2.9
openai==1.51.2
pandas==1.5.3
pandasai==2.2.12
psycopg2-binary==2.9.9
pydantic==2.9.2
sqlglot==25.2.0
tiktoken==0.7.0
urllib3==2.2.3
uvicorn[standard]==0.32.0
vertexai==1.68.0

**Comment by LarFii** [comment]
好的

**Comment by LarFii** [comment]
目前我们没有找到这个问题发生的原因，hnswlib的问题你看看可不可以参考[issue#24](https://github.com/HKUDS/LightRAG/issues/24)的解决方案

**Comment by baijumohamed** [comment]
did anyone manage to resolve this issue ? appreciate your pointers.

I am getting the same error in windows pycharm  python version 3.11.1

**Comment by Rainismer** [comment]
@baijumohamed Try upgrading chroma to the latest version.

**Comment by soapun** [comment]
@baijumohamed 

Python 3.12.7

Resolved this by excluding lock objects from pickling in CookieJar and ConnectionPool

```
import copyreg
from http.cookiejar import CookieJar
from httpcore import ConnectionPool

def save_coookiejar(obj: CookieJar):
    return obj.__class__, (obj._policy,)

def save_connectionpool(obj: ConnectionPool):
    return obj.__class__, (
        obj._ssl_context,
        obj._proxy,
        obj._max_connections,
        obj._max_keepalive_connections,
        obj._keepalive_expiry,
        obj._http1,
        obj._http2,
        obj._retries,
        obj._local_address,
        obj._uds,
        obj._network_backend,
        obj._socket_options
    )

copyreg.pickle(CookieJar, save_coookiejar)
copyreg.pickle(ConnectionPool, save_connectionpool)
```
