### ISSUE TITLE
laleEmor; al te irat arav irersirs exeot for te contention axis must atch exactly, but alono dimansin l. the anavat inex0 has size 1536 ad te anrav at iex l hes sie 768

### ISSUE THREAD

**Issue by hjing100** [HKUDS/LightRAG#244]
你好，还是有以上报错。

**Comment by hjing100** [comment]
INF0 :light rag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
File "/data/zhj/projects/rag/LightRAG-main/test01/example08 lightrag.py", line 85, in {<}module{>}
rag.insert (f .read( ))
File "/data/zhj/projects/rag/LightRAG-main/light rag/lightrag .py", line 167, in insert
retum loop.mn until complete(self.ainsert(st ring or st rings) )
File "/data/anaccnda3/envs/test39/lib/pythan3.9/asyncio/base events.py", line 642, in run ntil complete
retum future. result()
File "/data/zhj/projects/rag/ightRAG-main/light rag/lightrag .py", line 211, in ainsert
await self.chunks vdb.upsert (inserting chunks)
File "/data/zhj/projects/rag/ightRAG-main/light rag/storage.py", line 100, in upsert
results =self. client .upsert(datas-list data)
File "/data/anaconda3/envs/test39/lib/pythan3.9/site-packages/nano vectordb/cbs.py", line 108, in ypsert
self. storage["matrix"l= np.vstack([self. storage["matrix"l, new matrix])
File "/dat a/anacanda3/envs/test39/lib/pythan3.9/site-packages/numpy/core/shape base.py", line 289, in vstack
retum nx.concatenate(arrs, 0, dtype dtype, casting=casting)
ValueError: all te irat arav irersirs exeot for te contention axis must atch exactly, but alono dimansin l. the anavat inex0 has size 1536 ad te anrav at iex l hes sie 7f8

**Comment by hjing100** [comment]
难道是因为utlis.py做了以下改动？：

**Comment by hjing100** [comment]
难道是因为utils.py做了以下改动：ENCODER = AutoTokenizer.from_pretrained(
        "/data/qwen2-72b-instruct", device_map="auto", trust_remote_code=True
    )

**Comment by hjing100** [comment]
2024-11-08 10:40:17,021 - lightrag - INFO - Logger initialized for working directory: ./dickens
2024-11-08 10:40:17,021 - lightrag - DEBUG - LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 1536, 'max_token_size': 8192, 'func': <function embedding_func at 0x0000016D51D485E0>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function llm_model_func at 0x0000016D51A4F0D0>,
  llm_model_name = meta-llama/Llama-3.2-1B-Instruct,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  llm_model_kwargs = {},
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x0000016D7C6DCCA0>

2024-11-08 10:40:17,022 - lightrag - INFO - Load KV full_docs with 0 data
2024-11-08 10:40:17,022 - lightrag - INFO - Load KV text_chunks with 0 data
2024-11-08 10:40:17,023 - lightrag - INFO - Load KV llm_response_cache with 0 data
2024-11-08 10:40:17,024 - lightrag - INFO - Creating a new event loop in a sub-thread.
2024-11-08 10:40:17,025 - lightrag - INFO - [New Docs] inserting 1 docs
2024-11-08 10:40:17,338 - lightrag - INFO - [New Chunks] inserting 14 chunks
2024-11-08 10:40:17,338 - lightrag - INFO - Inserting 14 vectors to chunks
2024-11-08 10:40:21,268 - lightrag - INFO - [Entity Extraction]...
2024-11-08 10:41:06,260 - lightrag - INFO - Writing graph with 0 nodes, 0 edges


难道是因为utils.py做了以下改动：ENCODER = AutoTokenizer.from_pretrained(
"/data/qwen2-72b-instruct", device_map="auto", trust_remote_code=True
)

def encode_string_by_tiktoken(content: str, model_name: str = "gpt-4o"):
    global ENCODER
    # if ENCODER is None:
    #     ENCODER = tiktoken.encoding_for_model(model_name)

    # model_inputs = ENCODER(content)
    # input_ids = model_inputs.input_ids.cup().numpy()[0]
    # tokens = input_ids

    model_inputs = ENCODER(content)
    input_ids = model_inputs.input_ids
    tokens = input_ids

    return tokens


def decode_tokens_by_tiktoken(tokens: list[int], model_name: str = "gpt-4o"):
    global ENCODER
    # if ENCODER is None:
    #     ENCODER = tiktoken.encoding_for_model(model_name)
    tokens = torch.IntTensor(tokens)
    content = ENCODER.decode(tokens)
    return content

运行代码是：
import os
import numpy as np
from lightrag import LightRAG, QueryParam
# from lightrag.llm import gpt_4o_mini_complete, gpt_4o_complete
# from lightrag.llm import openai_complete_if_cache, openai_embedding
from lightrag.utils import EmbeddingFunc
from lightrag.llm import hf_model_complete, hf_embedding
from transformers import AutoModel, AutoTokenizer
import time

#########
# Uncomment the below two lines if running in a jupyter notebook to handle the async nature of rag.insert()
# import nest_asyncio
# nest_asyncio.apply()
#########

WORKING_DIR = "./dickens"
# API_KEY = "sk-eBfT5eAK3JzCklBJD756Ff738372486aA233F1CcF6Fa7bAe"
# OPENAI_BASE_URL = "https://api.xiaoai.plus/v1"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

# Initialize LightRAG with Hugging Face model
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,  # Use Hugging Face model for text generation
    llm_model_name='/data/qwen2-72b-instruct',  # Model name from Hugging Face
    # tiktoken_model_name ='meta-llama/Llama-3.1-8B-Instruct',
    # Use Hugging Face embedding function
    embedding_func=EmbeddingFunc(
        embedding_dim=1536,
        max_token_size=8192,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained("/data/bce-embedding-base_v1"),
            embed_model=AutoModel.from_pretrained("/data/bce-embedding-base_v1")
        )
    ),
)
# ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4096 and the array at index 1 has size 1536
# embedding_dim=4096 -> embedding_dim=1536

with open(r"D:\code\LightRAG-main\book.txt","r",encoding="utf-8") as f:
    rag.insert(f.read())


query_ = "这篇文章主要讲了些什么？"
print(rag.query(query_, param=QueryParam(mode="global")))
print("*******************")
time.sleep(2)

**Comment by hjing100** [comment]
2024-11-08 10:40:17,021 - lightrag - INFO - Logger initialized for working directory: ./dickens
2024-11-08 10:40:17,021 - lightrag - DEBUG - LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 1536, 'max_token_size': 8192, 'func': <function embedding_func at 0x0000016D51D485E0>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function llm_model_func at 0x0000016D51A4F0D0>,
  llm_model_name = meta-llama/Llama-3.2-1B-Instruct,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  llm_model_kwargs = {},
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x0000016D7C6DCCA0>

2024-11-08 10:40:17,022 - lightrag - INFO - Load KV full_docs with 0 data
2024-11-08 10:40:17,022 - lightrag - INFO - Load KV text_chunks with 0 data
2024-11-08 10:40:17,023 - lightrag - INFO - Load KV llm_response_cache with 0 data
2024-11-08 10:40:17,024 - lightrag - INFO - Creating a new event loop in a sub-thread.
2024-11-08 10:40:17,025 - lightrag - INFO - [New Docs] inserting 1 docs
2024-11-08 10:40:17,338 - lightrag - INFO - [New Chunks] inserting 14 chunks
2024-11-08 10:40:17,338 - lightrag - INFO - Inserting 14 vectors to chunks
2024-11-08 10:40:21,268 - lightrag - INFO - [Entity Extraction]...
2024-11-08 10:41:06,260 - lightrag - INFO - Writing graph with 0 nodes, 0 edges


难道是因为utils.py做了以下改动：ENCODER = AutoTokenizer.from_pretrained(
"/data/qwen2-72b-instruct", device_map="auto", trust_remote_code=True
)

def encode_string_by_tiktoken(content: str, model_name: str = "gpt-4o"):
    global ENCODER

    model_inputs = ENCODER(content)
    input_ids = model_inputs.input_ids
    tokens = input_ids

    return tokens


def decode_tokens_by_tiktoken(tokens: list[int], model_name: str = "gpt-4o"):
    global ENCODER

    tokens = torch.IntTensor(tokens)
    content = ENCODER.decode(tokens)
    return content

运行代码是：
import os
import numpy as np
from lightrag import LightRAG, QueryParam
# from lightrag.llm import gpt_4o_mini_complete, gpt_4o_complete
# from lightrag.llm import openai_complete_if_cache, openai_embedding
from lightrag.utils import EmbeddingFunc
from lightrag.llm import hf_model_complete, hf_embedding
from transformers import AutoModel, AutoTokenizer
import time


WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)


rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,  # Use Hugging Face model for text generation
    llm_model_name='/data/qwen2-72b-instruct',  # Model name from Hugging Face

    embedding_func=EmbeddingFunc(
        embedding_dim=1536,
        max_token_size=8192,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained("/data/bce-embedding-base_v1"),
            embed_model=AutoModel.from_pretrained("/data/bce-embedding-base_v1")
        )
    ),
)

with open(r"D:\code\LightRAG-main\book.txt","r",encoding="utf-8") as f:
    rag.insert(f.read())


query_ = "这篇文章主要讲了些什么？"
print(rag.query(query_, param=QueryParam(mode="global")))
print("*******************")
time.sleep(2)

**Comment by hjing100** [comment]
2024-11-08 10:40:17,021 - lightrag - INFO - Logger initialized for working directory: ./dickens
2024-11-08 10:40:17,021 - lightrag - DEBUG - LightRAG init with param:
  working_dir = ./dickens,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 1536, 'max_token_size': 8192, 'func': <function embedding_func at 0x0000016D51D485E0>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function llm_model_func at 0x0000016D51A4F0D0>,
  llm_model_name = meta-llama/Llama-3.2-1B-Instruct,
  llm_model_max_token_size = 32768,
  llm_model_max_async = 16,
  llm_model_kwargs = {},
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x0000016D7C6DCCA0>

2024-11-08 10:40:17,022 - lightrag - INFO - Load KV full_docs with 0 data
2024-11-08 10:40:17,022 - lightrag - INFO - Load KV text_chunks with 0 data
2024-11-08 10:40:17,023 - lightrag - INFO - Load KV llm_response_cache with 0 data
2024-11-08 10:40:17,024 - lightrag - INFO - Creating a new event loop in a sub-thread.
2024-11-08 10:40:17,025 - lightrag - INFO - [New Docs] inserting 1 docs
2024-11-08 10:40:17,338 - lightrag - INFO - [New Chunks] inserting 14 chunks
2024-11-08 10:40:17,338 - lightrag - INFO - Inserting 14 vectors to chunks
2024-11-08 10:40:21,268 - lightrag - INFO - [Entity Extraction]...
2024-11-08 10:41:06,260 - lightrag - INFO - Writing graph with 0 nodes, 0 edges


难道是因为utils.py做了以下改动：ENCODER = AutoTokenizer.from_pretrained(
"/data/qwen2-72b-instruct", device_map="auto", trust_remote_code=True
)

def encode_string_by_tiktoken(content: str, model_name: str = "gpt-4o"):
    global ENCODER

    model_inputs = ENCODER(content)
    input_ids = model_inputs.input_ids
    tokens = input_ids

    return tokens


def decode_tokens_by_tiktoken(tokens: list[int], model_name: str = "gpt-4o"):
    global ENCODER

    tokens = torch.IntTensor(tokens)
    content = ENCODER.decode(tokens)
    return content

运行代码是：
import os
import numpy as np
from lightrag import LightRAG, QueryParam

from lightrag.utils import EmbeddingFunc
from lightrag.llm import hf_model_complete, hf_embedding
from transformers import AutoModel, AutoTokenizer
import time


WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)


rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,  # Use Hugging Face model for text generation
    llm_model_name='/data/qwen2-72b-instruct',  # Model name from Hugging Face

    embedding_func=EmbeddingFunc(
        embedding_dim=1536,
        max_token_size=8192,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained("/data/bce-embedding-base_v1"),
            embed_model=AutoModel.from_pretrained("/data/bce-embedding-base_v1")
        )
    ),
)

with open(r"D:\code\LightRAG-main\book.txt","r",encoding="utf-8") as f:
    rag.insert(f.read())


query_ = "这篇文章主要讲了些什么？"
print(rag.query(query_, param=QueryParam(mode="global")))
print("*******************")
time.sleep(2)

**Comment by hjing100** [comment]
难道是因为utils.py做了以下改动：ENCODER = AutoTokenizer.from_pretrained(
"/data/qwen2-72b-instruct", device_map="auto", trust_remote_code=True
)

def encode_string_by_tiktoken(content: str, model_name: str = "gpt-4o"):
    global ENCODER

    model_inputs = ENCODER(content)
    input_ids = model_inputs.input_ids
    tokens = input_ids

    return tokens


def decode_tokens_by_tiktoken(tokens: list[int], model_name: str = "gpt-4o"):
    global ENCODER

    tokens = torch.IntTensor(tokens)
    content = ENCODER.decode(tokens)
    return content

运行代码是：
import os
import numpy as np
from lightrag import LightRAG, QueryParam

from lightrag.utils import EmbeddingFunc
from lightrag.llm import hf_model_complete, hf_embedding
from transformers import AutoModel, AutoTokenizer
import time


WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)


rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,  # Use Hugging Face model for text generation
    llm_model_name='/data/qwen2-72b-instruct',  # Model name from Hugging Face

    embedding_func=EmbeddingFunc(
        embedding_dim=1536,
        max_token_size=8192,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained("/data/bce-embedding-base_v1"),
            embed_model=AutoModel.from_pretrained("/data/bce-embedding-base_v1")
        )
    ),
)

with open(r"D:\code\LightRAG-main\book.txt","r",encoding="utf-8") as f:
    rag.insert(f.read())


query_ = "这篇文章主要讲了些什么？"
print(rag.query(query_, param=QueryParam(mode="global")))
print("*******************")
time.sleep(2)

**Comment by Aniwine** [comment]
use another embedding model,like nomic-embed-text,don't forget mkdir a new workdir ,it works for me

**Comment by hjing100** [comment]
> use another embedding model,like nomic-embed-text,don't forget mkdir a new workdir ,it works for me

It's not work for me.
bce-embedding-base_v1 dimensions is 768, so chang:
lightrag.py
node2vec_params: dict = field(
        default_factory=lambda: {
            "dimensions": 768,  # 1536,
            "num_walks": 10,
            "walk_length": 40,
            "window_size": 2,
            "iterations": 3,
            "random_seed": 3,
        }
    )

lightrag_hf_demo.py
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=hf_model_complete,  
    llm_model_name='/data/qwen2-72b-instruct',  
    embedding_func=EmbeddingFunc(
        embedding_dim=768,  # 1536,
        max_token_size=8192,
        func=lambda texts: hf_embedding(
            texts,
            tokenizer=AutoTokenizer.from_pretrained("/data/bce-embedding-base_v1"),
            embed_model=AutoModel.from_pretrained("/data/bce-embedding-base_v1")
        )
    ),
)

**Comment by hjing100** [comment]
have another question:

**Comment by hjing100** [comment]
排查出原因是，是因为安装了tensorflow，卸载了就好了。
刚开始以为是我的改动导致代码里哪里有点问题，后来运行qwen推理发现也有同样的问题，才发现是import tensorflow就会报改错。
而且LightRAG外网环境没有tensorflow包的需要(tensorflow安装是之前别的项目需要):
(LightRAG) C:\Users\lenovo>pip list
Package Version Editable project location

accelerate 1.1.1
aioboto3 13.2.0
aiobotocore 2.15.2
aiofiles 24.1.0
aiohappyeyeballs 2.4.3
aiohttp 3.10.10
aioitertools 0.12.0
aiosignal 1.3.1
annotated-types 0.7.0
anyio 4.6.2.post1
anytree 2.12.1
asttokens 2.4.1
async-timeout 4.0.3
attrs 24.2.0
autograd 1.7.0
beartype 0.18.5
boto3 1.35.36
botocore 1.35.36
certifi 2024.8.30
charset-normalizer 3.4.0
colorama 0.4.6
contourpy 1.3.0
cycler 0.12.1
decorator 5.1.1
distro 1.9.0
exceptiongroup 1.2.2
executing 2.1.0
filelock 3.16.1
fonttools 4.54.1
frozenlist 1.5.0
fsspec 2024.10.0
gensim 4.3.3
graspologic 3.4.1
graspologic-native 1.2.1
h11 0.14.0
hnswlib 0.8.0
httpcore 1.0.6
httpx 0.27.2
huggingface-hub 0.26.2
hyppo 0.4.0
idna 3.10
importlib_resources 6.4.5
ipython 8.18.1
jedi 0.19.1
Jinja2 3.1.4
jiter 0.7.0
jmespath 1.0.1
joblib 1.4.2
jsonpickle 3.4.2
kiwisolver 1.4.7
lightrag-hku 0.0.8 d:\code\lightrag-main
llvmlite 0.43.0
MarkupSafe 3.0.2
matplotlib 3.9.2
matplotlib-inline 0.1.7
mpmath 1.3.0
multidict 6.1.0
nano-vectordb 0.0.4.1
networkx 3.2.1
numba 0.60.0
numpy 1.26.4
ollama 0.3.3
openai 1.54.3
packaging 24.1
pandas 2.2.3
parso 0.8.4
patsy 0.5.6
pillow 11.0.0
pip 24.2
POT 0.9.5
prompt_toolkit 3.0.48
propcache 0.2.0
psutil 6.1.0
pure_eval 0.2.3
pydantic 2.9.2
pydantic_core 2.23.4
Pygments 2.18.0
pynndescent 0.5.13
pyparsing 3.2.0
python-dateutil 2.9.0.post0
pytz 2024.2
pyvis 0.3.2
PyYAML 6.0.2
regex 2024.11.6
requests 2.32.3
s3transfer 0.10.3
safetensors 0.4.5
scikit-learn 1.5.2
scipy 1.12.0
seaborn 0.13.2
setuptools 75.1.0
six 1.16.0
smart-open 7.0.5
sniffio 1.3.1
stack-data 0.6.3
statsmodels 0.14.4
sympy 1.13.1
tenacity 9.0.0
threadpoolctl 3.5.0
tiktoken 0.8.0
tokenizers 0.20.3
torch 2.5.1
tqdm 4.67.0
traitlets 5.14.3
transformers 4.46.2
typing_extensions 4.12.2
tzdata 2024.2
umap-learn 0.5.7
urllib3 1.26.20
wcwidth 0.2.13
wheel 0.44.0
wrapt 1.16.0
xxhash 3.5.0
yarl 1.17.1
zipp 3.20.2

(LightRAG) C:\Users\lenovo>
