### ISSUE TITLE
openai ratelimit error and ollama too slow on cpu

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [HKUDS/LightRAG#293]
code:
```
import os
import time
from tqdm.auto import tqdm

os.environ['OPENAI_API_KEY']='abc'

import pdfplumber
from lightrag import LightRAG, QueryParam
from lightrag.llm import ollama_model_complete, ollama_embedding
from lightrag.utils import EmbeddingFunc

from lightrag.llm import gpt_4o_mini_complete

WORKING_DIR = "../run_2"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

# ========================================  OpenAI  ======================================== #
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=gpt_4o_mini_complete,
    # llm_model_func=gpt_4o_complete
)
# ========================================  Ollama  ======================================== #
# rag = LightRAG(
#    working_dir=WORKING_DIR,
#    chunk_token_size=1200,
#    llm_model_func=ollama_model_complete,
#    llm_model_name="llama3.2:1b", #, 
#    llm_model_max_async=1,
#    llm_model_max_token_size=32768,
#    llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 32768}},
#    embedding_func=EmbeddingFunc(
#        embedding_dim=768,
#        max_token_size=8192,
#        func=lambda texts: ollama_embedding(texts, embed_model="nomic-embed-text", host="http://localhost:11434"),
#    ),
# )


pdf_path = "../CompaniesAct2013.pdf" #Constitution_of_India.pdf
pdf_text = ""
with pdfplumber.open(pdf_path) as pdf:
    for page in tqdm(pdf.pages[14:20], desc='Extract Text from pages', total=2):
        pdf_text += page.extract_text() + "\n"


rag.insert(pdf_text)


```

INFO:lightrag:Logger initialized for working directory: ../run_2
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_entities.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_relationships.json'} 0 data
INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_chunks.json'} 0 data
Extract Text from pages: 6it [00:02,  2.67it/s]                                                                                                                       
INFO:lightrag:[New Docs] inserting 1 docs
INFO:lightrag:[New Chunks] inserting 5 chunks
INFO:lightrag:Inserting 5 vectors to chunks
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.449477 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.878241 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.389104 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.882345 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.469158 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /embeddings in 0.888185 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests"
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/llm.py", line 550, in openai_embedding
    response = await openai_async_client.embeddings.create(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/resources/embeddings.py", line 236, in create
    return await self._post(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1839, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1533, in request
    return await self._request(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1619, in _request
    return await self._retry_request(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1666, in _retry_request
    return await self._request(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1619, in _request
    return await self._retry_request(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1666, in _retry_request
    return await self._request(
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1634, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/1_run_ollama.py", line 63, in <module>
    rag.insert(pdf_text)
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/lightrag.py", line 227, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/lightrag.py", line 271, in ainsert
    await self.chunks_vdb.upsert(inserting_chunks)
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/storage.py", line 98, in upsert
    embeddings_list = await asyncio.gather(
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/utils.py", line 89, in wait_func
    result = await func(*args, **kwargs)
  File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/utils.py", line 45, in __call__
    return await self.func(*args, **kwargs)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x73ece6a8e8c0 state=finished raised RateLimitError>]

**Comment by LarFii** [comment]
This is indeed a challenging issue to avoid. However, you can add a delay and retry the insertion process after encountering a rate limit error with OpenAI. Since already extracted content is cached, it won't be reprocessed. Unfortunately, for local models, we currently don't have an effective way to significantly improve the speed on CPU.

**Comment by m-aliabbas** [comment]
Facing same issue 


  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/lightrag/utils.py", line 77, in wait_func
    result = await func(*args, **kwargs)
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/lightrag/llm.py", line 60, in gpt_4o_mini_complete
    return await openai_complete_if_cache(
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/Users/ali/anaconda3/envs/graph_rag/lib/python3.10/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1541b04f0 state=finished raised RateLimitError>]



how we can add a delay?

**Comment by m-aliabbas** [comment]
Facing rate limit (per minute) issue
I added time.sleep in `openai/_base_client.py", line 1611, in _request`


```
    def _make_status_error_from_response(
        self,
        response: httpx.Response,
    ) -> APIStatusError:
        if response.is_closed and not response.is_stream_consumed:
            # We can't read the response body as it has been closed
            # before it was read. This can happen if an event hook
            # raises a status error.
            body = None
            err_msg = f"Error code: {response.status_code}"
        else:
            err_text = response.text.strip()
            body = err_text

            try:
                body = json.loads(err_text)
                err_msg = f"Error code: {response.status_code} - {body}"
            except Exception:
                err_msg = err_text or f"Error code: {response.status_code}"
        time.sleep(1.0)
        return self._make_status_error(err_msg, body=body, response=response)
        
```
    and its working

**Comment by Arslan-Mehmood1** [comment]
where is this file ? openai/_base_client.py", line 1611, in _request

**Comment by git9875** [comment]
> where is this file ? openai/_base_client.py", line 1611, in _request

I found it here but on line 380 :
./.venv/lib/python3.11/site-packages/openai/_base_client.py

----

I ran this program but with a much larger text file:
python3 lightrag_openai_demo.py

It looked like it solved the problem at first, but then it happened again.
Extracting entities from chunks:  19%|███████████████████▊                                                                                       | 45/243 [01:31<13:35,  4.12s/chunk]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 1.392000 seconds
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 1.148000 seconds


Finally, it broke with this error response:
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4o-mini in organization org-3EfNuOTOsuBTQxJg5nBEBipX on tokens per min (TPM): Limit 200000, Used 198923, Requested 4997. Please try again in 1.176s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

Great, now I've got another error that says "Rate limit reached for ... tokens per min".

From up above "Extracting entities from chunks", that means it's sending all of the contents to OpenAI to do the entity extraction? I thought it had an internal method or Graph database (neo4j) to automatically do that, or was that all just hype?!

**Comment by andrewlwn77** [comment]
> code:
> 
> ```
> import os
> import time
> from tqdm.auto import tqdm
> 
> os.environ['OPENAI_API_KEY']='abc'
> 
> import pdfplumber
> from lightrag import LightRAG, QueryParam
> from lightrag.llm import ollama_model_complete, ollama_embedding
> from lightrag.utils import EmbeddingFunc
> 
> from lightrag.llm import gpt_4o_mini_complete
> 
> WORKING_DIR = "../run_2"
> 
> if not os.path.exists(WORKING_DIR):
>     os.mkdir(WORKING_DIR)
> 
> # ========================================  OpenAI  ======================================== #
> rag = LightRAG(
>     working_dir=WORKING_DIR,
>     llm_model_func=gpt_4o_mini_complete,
>     # llm_model_func=gpt_4o_complete
> )
> # ========================================  Ollama  ======================================== #
> # rag = LightRAG(
> #    working_dir=WORKING_DIR,
> #    chunk_token_size=1200,
> #    llm_model_func=ollama_model_complete,
> #    llm_model_name="llama3.2:1b", #, 
> #    llm_model_max_async=1,
> #    llm_model_max_token_size=32768,
> #    llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 32768}},
> #    embedding_func=EmbeddingFunc(
> #        embedding_dim=768,
> #        max_token_size=8192,
> #        func=lambda texts: ollama_embedding(texts, embed_model="nomic-embed-text", host="http://localhost:11434"),
> #    ),
> # )
> 
> 
> pdf_path = "../CompaniesAct2013.pdf" #Constitution_of_India.pdf
> pdf_text = ""
> with pdfplumber.open(pdf_path) as pdf:
>     for page in tqdm(pdf.pages[14:20], desc='Extract Text from pages', total=2):
>         pdf_text += page.extract_text() + "\n"
> 
> 
> rag.insert(pdf_text)
> ```
> 
> INFO:lightrag:Logger initialized for working directory: ../run_2 INFO:lightrag:Load KV llm_response_cache with 0 data INFO:lightrag:Load KV full_docs with 0 data INFO:lightrag:Load KV text_chunks with 0 data INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_entities.json'} 0 data INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_relationships.json'} 0 data INFO:nano-vectordb:Init {'embedding_dim': 1536, 'metric': 'cosine', 'storage_file': '../run_2/vdb_chunks.json'} 0 data Extract Text from pages: 6it [00:02, 2.67it/s] INFO:lightrag:[New Docs] inserting 1 docs INFO:lightrag:[New Chunks] inserting 5 chunks INFO:lightrag:Inserting 5 vectors to chunks INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.449477 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.878241 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.389104 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.882345 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.469158 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:openai._base_client:Retrying request to /embeddings in 0.888185 seconds INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 429 Too Many Requests" INFO:lightrag:Writing graph with 0 nodes, 0 edges Traceback (most recent call last): File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/**init**.py", line 114, in **call** result = await fn(*args, **kwargs) File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/llm.py", line 550, in openai_embedding response = await openai_async_client.embeddings.create( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/resources/embeddings.py", line 236, in create return await self._post( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1839, in post return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1533, in request return await self._request( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1619, in _request return await self._retry_request( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1666, in _retry_request return await self._request( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1619, in _request return await self._retry_request( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1666, in _retry_request return await self._request( File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/openai/_base_client.py", line 1634, in _request raise self._make_status_error_from_response(err.response) from None openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/1_run_ollama.py", line 63, in rag.insert(pdf_text) File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/lightrag.py", line 227, in insert return loop.run_until_complete(self.ainsert(string_or_strings)) File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/lightrag.py", line 271, in ainsert await self.chunks_vdb.upsert(inserting_chunks) File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/storage.py", line 98, in upsert embeddings_list = await asyncio.gather( File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/utils.py", line 89, in wait_func result = await func(*args, **kwargs) File "/home/arslan/Data/Learning/side_projects/LighRAG_legal_doc/LightRAG/lightrag/utils.py", line 45, in **call** return await self.func(*args, **kwargs) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/**init**.py", line 189, in async_wrapped return await copy(fn, *args, **kwargs) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/**init**.py", line 111, in **call** do = await self.iter(retry_state=retry_state) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/asyncio/**init**.py", line 153, in iter result = await action(retry_state) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner return call(*args, **kwargs) File "/home/arslan/.virtualenvs/lightrag/lib/python3.10/site-packages/tenacity/**init**.py", line 419, in exc_check raise retry_exc from fut.exception() tenacity.RetryError: RetryError[<Future at 0x73ece6a8e8c0 state=finished raised RateLimitError>]

@Arslan-Mehmood1 I just process the document really slowly.

You can see my code here:
`
        # chunk_size: int = 512,  # Number of tokens per chunk
        # delay_between_chunks: float = 2.0,  # Delay in seconds between chunk processing
        # Split the text into smaller chunks (by tokens or by character length)
        chunks = [text_content[i:i+chunk_size] for i in range(0, len(text_content), chunk_size)]

        # Initialize LightRAG with rate-limited function
        rag = LightRAG(
            working_dir=working_dir,
            llm_model_func=gpt_4o_complete,
        )

        # Process each chunk with LightRAG
        for idx, chunk in enumerate(chunks):
            print(f"Processing chunk {idx+1}/{len(chunks)}")
            try:
                await rag.ainsert(chunk)
            except Exception as e:
                print(f"Error processing chunk {idx+1}: {str(e)}")
            await asyncio.sleep(delay_between_chunks)  # Pause between chunk processing
`

Just play around with the params until you are happy

**Comment by git9875** [comment]
I thought that the llm_model_max_async parameter would fix this issue. This should be fine I think:
llm_model_max_async = 10

**Comment by andrewlwn77** [comment]
> I thought that the llm_model_max_async parameter would fix this issue. This should be fine I think: llm_model_max_async = 10

Even with my super slow code I still get 429s, but it works its way through without me having to do anything:

2024-12-10 19:16:31,144 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-12-10 19:16:31,357 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2024-12-10 19:16:31,358 - openai._base_client - INFO - Retrying request to /chat/completions in 1.784000 seconds
2024-12-10 19:16:34,505 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
⠙ Processed 1 chunks, 6 entities(duplicated), 2 relations(duplicated)
2024-12-10 19:16:34,516 - lightrag - INFO - Inserting 6 vectors to entities
2024-12-10 19:16:35,170 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:35,465 - lightrag - INFO - Inserting 2 vectors to relationships
2024-12-10 19:16:35,913 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:36,248 - lightrag - INFO - Writing graph with 458 nodes, 258 edges
Processing chunk 147/1360
2024-12-10 19:16:38,283 - lightrag - INFO - [New Docs] inserting 1 docs
2024-12-10 19:16:38,284 - lightrag - INFO - [New Chunks] inserting 1 chunks
2024-12-10 19:16:38,284 - lightrag - INFO - Inserting 1 vectors to chunks
2024-12-10 19:16:38,663 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:38,750 - lightrag - INFO - [Entity Extraction]...
2024-12-10 19:16:40,830 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-12-10 19:16:41,056 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2024-12-10 19:16:41,056 - openai._base_client - INFO - Retrying request to /chat/completions in 2.390000 seconds
2024-12-10 19:16:45,859 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
⠙ Processed 1 chunks, 8 entities(duplicated), 3 relations(duplicated)
2024-12-10 19:16:45,862 - lightrag - INFO - Inserting 8 vectors to entities
2024-12-10 19:16:46,449 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:46,817 - lightrag - INFO - Inserting 3 vectors to relationships
2024-12-10 19:16:47,280 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:47,769 - lightrag - INFO - Writing graph with 463 nodes, 261 edges
Processing chunk 148/1360
2024-12-10 19:16:49,844 - lightrag - INFO - [New Docs] inserting 1 docs
2024-12-10 19:16:49,845 - lightrag - INFO - [New Chunks] inserting 1 chunks
2024-12-10 19:16:49,846 - lightrag - INFO - Inserting 1 vectors to chunks
2024-12-10 19:16:50,122 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:16:50,208 - lightrag - INFO - [Entity Extraction]...
2024-12-10 19:16:57,480 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-12-10 19:16:59,880 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
⠙ Processed 1 chunks, 8 entities(duplicated), 4 relations(duplicated)
2024-12-10 19:16:59,884 - lightrag - INFO - Inserting 8 vectors to entities
2024-12-10 19:17:00,228 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:17:00,564 - lightrag - INFO - Inserting 4 vectors to relationships
2024-12-10 19:17:01,073 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:17:01,620 - lightrag - INFO - Writing graph with 470 nodes, 265 edges
Processing chunk 149/1360
2024-12-10 19:17:03,688 - lightrag - INFO - [New Docs] inserting 1 docs
2024-12-10 19:17:03,689 - lightrag - INFO - [New Chunks] inserting 1 chunks
2024-12-10 19:17:03,689 - lightrag - INFO - Inserting 1 vectors to chunks
2024-12-10 19:17:04,077 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:17:04,171 - lightrag - INFO - [Entity Extraction]...
2024-12-10 19:17:08,010 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2024-12-10 19:17:10,540 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
⠙ Processed 1 chunks, 10 entities(duplicated), 3 relations(duplicated)
2024-12-10 19:17:10,547 - lightrag - INFO - Inserting 10 vectors to entities
2024-12-10 19:17:11,168 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:17:11,545 - lightrag - INFO - Inserting 3 vectors to relationships
2024-12-10 19:17:12,036 - httpx - INFO - HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2024-12-10 19:17:12,455 - lightrag - INFO - Writing graph with 478 nodes, 267 edges

**Comment by boloboloda** [comment]
same issues for me, Extracting entities and relationships process is so slow.
