### ISSUE TITLE
ollama._types.ResponseError

### ISSUE THREAD

**Issue by heyuqi1970** [HKUDS/LightRAG#305]
windows 10 运行ollama demo，ollama ==0.4.2, python==3.9
![image](https://github.com/user-attachments/assets/30ec8349-b6bb-4d9b-80d2-0a771cd3bf61)

提示错误：

```
INFO:lightrag:[Entity Extraction]...
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 503 Service Unavailable"
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "C:\Users\heyuqi\dev\rag\LightRAG\examples\lightrag_ollama_demo.py", line 35, in <module>
    rag.insert(f.read())
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\lightrag.py", line 227, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "C:\Users\heyuqi\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\lightrag.py", line 276, in ainsert
    maybe_new_kg = await extract_entities(
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\operate.py", line 333, in extract_entities
    results = await asyncio.gather(
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\operate.py", line 276, in _process_single_content
    glean_result = await use_llm_func(continue_prompt, history_messages=history)
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\utils.py", line 89, in wait_func
    result = await func(*args, **kwargs)
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\llm.py", line 523, in ollama_model_complete
    return await ollama_model_if_cache(
  File "C:\Users\heyuqi\dev\rag\LightRAG\lightrag\llm.py", line 319, in ollama_model_if_cache
    response = await ollama_client.chat(model=model, messages=messages, **kwargs)
  File "C:\Users\heyuqi\dev\rag\venv\lib\site-packages\ollama\_client.py", line 654, in chat
    return await self._request_stream(
  File "C:\Users\heyuqi\dev\rag\venv\lib\site-packages\ollama\_client.py", line 518, in _request_stream
    response = await self._request(*args, **kwargs)
  File "C:\Users\heyuqi\dev\rag\venv\lib\site-packages\ollama\_client.py", line 488, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError
```

**Comment by penghd** [comment]
这是解析不出关系，用qwen2.5:14b
再不行就设置上下文12800
如果显存不够还是买4090吧😊
