### ISSUE TITLE
调用vllm-server/sglang部署的模型容易出现ConnectionError

### ISSUE THREAD

**Issue by RoacherM** [HKUDS/LightRAG#33]
使用的配置信息如下和报错信息如下，尝试设置了llm_model_max_async=2，但是还是会频繁出现该问题，还有哪些地方的参数可以修改么
目前调用的是用sglang部署的qwen2-72B（tp=4, max_tokens=16K）

`
/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
INFO:lightrag:Logger initialized for working directory: ./db/training_on_benchmark_qwen2.5-72b-async1
DEBUG:lightrag:LightRAG init with param:
  working_dir = ./db/training_on_benchmark_qwen2.5-72b-async1,
  chunk_token_size = 1200,
  chunk_overlap_token_size = 100,
  tiktoken_model_name = gpt-4o-mini,
  entity_extract_max_gleaning = 1,
  entity_summary_to_max_tokens = 500,
  node_embedding_algorithm = node2vec,
  node2vec_params = {'dimensions': 1536, 'num_walks': 10, 'walk_length': 40, 'window_size': 2, 'iterations': 3, 'random_seed': 3},
  embedding_func = {'embedding_dim': 384, 'max_token_size': 5000, 'func': <function hf_embedding at 0x15860c700>},
  embedding_batch_num = 32,
  embedding_func_max_async = 16,
  llm_model_func = <function vllm_complete at 0x14309e4d0>,
  llm_model_name = meta-llama/Llama-3.2-1B-Instruct,
  llm_model_max_token_size = 16384,
  llm_model_max_async = 2,
  key_string_value_json_storage_cls = <class 'lightrag.storage.JsonKVStorage'>,
  vector_db_storage_cls = <class 'lightrag.storage.NanoVectorDBStorage'>,
  vector_db_storage_cls_kwargs = {},
  graph_storage_cls = <class 'lightrag.storage.NetworkXStorage'>,
  enable_llm_cache = True,
  addon_params = {},
  convert_response_to_json_func = <function convert_response_to_json at 0x104645510>

INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:lightrag:Loaded graph from ./db/training_on_benchmark_qwen2.5-72b-async1/graph_chunk_entity_relation.graphml with 0 nodes, 0 edges
INFO:nano-vectordb:Load (0, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './db/training_on_benchmark_qwen2.5-72b-async1/vdb_entities.json'} 0 data
INFO:nano-vectordb:Load (0, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './db/training_on_benchmark_qwen2.5-72b-async1/vdb_relationships.json'} 0 data
INFO:nano-vectordb:Load (9, 384) data
INFO:nano-vectordb:Init {'embedding_dim': 384, 'metric': 'cosine', 'storage_file': './db/training_on_benchmark_qwen2.5-72b-async1/vdb_chunks.json'} 9 data
INFO:lightrag:[New Docs] inserting 1 docs
INFO:lightrag:[New Chunks] inserting 9 chunks
INFO:lightrag:Inserting 9 vectors to chunks
INFO:lightrag:[Entity Extraction]...
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpcore/_async/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/openai/_base_client.py", line 1571, in _request
    response = await self._client.send(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/llm.py", line 53, in openai_complete_if_cache
    response = await openai_async_client.chat.completions.create(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1490, in create
    return await self._post(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
    return await self._request(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/test.py", line 70, in <module>
    rag.insert(f.read())
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/lightrag.py", line 164, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/lightrag.py", line 211, in ainsert
    maybe_new_kg = await extract_entities(
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/operate.py", line 332, in extract_entities
    results = await asyncio.gather(
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/operate.py", line 271, in _process_single_content
    final_result = await use_llm_func(hint_prompt)
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/utils.py", line 77, in wait_func
    result = await func(*args, **kwargs)
  File "/Users/byronvon/Desktop/Projects/Repos/LightRAG/lightrag/llm.py", line 187, in vllm_complete
    return await openai_complete_if_cache(
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 185, in async_wrapped
    return await fn(*args, **kwargs)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/Users/byronvon/miniconda3/envs/infinity/lib/python3.10/site-packages/tenacity/__init__.py", line 413, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1644d1de0 state=finished raised APIConnectionError>]
`

**Comment by LarFii** [comment]
我们目前还没有尝试过用sglang，这两天我们会尝试一下，尽快给你答复

**Comment by RoacherM** [comment]
> 我们目前还没有尝试过用sglang，这两天我们会尝试一下，尽快给你答复

感谢回复。我目前测试下来，连接本地部署的vllm/sglang服务的话（tp=4 qwen2.5-72B-awq）llm_model_max_async设置为2勉强能跑，但chunks一多，还是会出现connection error，怀疑是本地服务无法处理这么多请求导致的。

**Comment by LarFii** [comment]
如果是这样的话可以尝试多次少量的插入

**Comment by RoacherM** [comment]
这个问题我解决了，不是vllm-server的问题，而是本地开了VPN代理导致server connection error，关掉vpn或者stream设置为true都能解决这个问题。怀疑是VPN分流导致的。

**Comment by RoacherM** [comment]
我是改了下llm.py中的函数，仅供参考。
```
@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=4, max=10),
    retry=retry_if_exception_type((RateLimitError, APIConnectionError, Timeout)),
)
async def openai_complete_if_cache(
    model,
    prompt,
    system_prompt=None,
    history_messages=[],
    stream=False,
    base_url=None,
    api_key=None,
    **kwargs,
) -> str:
    if api_key:
        os.environ["OPENAI_API_KEY"] = api_key

    openai_async_client = (
        AsyncOpenAI() if base_url is None else AsyncOpenAI(base_url=base_url)
    )
    hashing_kv: BaseKVStorage = kwargs.pop("hashing_kv", None)
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})
    if hashing_kv is not None:
        args_hash = compute_args_hash(model, messages)
        if_cache_return = await hashing_kv.get_by_id(args_hash)
        if if_cache_return is not None:
            return if_cache_return["return"]

    if stream:
        # 初始化response
        full_response = ""
        response = await openai_async_client.chat.completions.create(
            model=model, messages=messages, stream=stream, **kwargs
        )

        async for chunk in response:
            content = chunk.choices[0].delta.content
            if content:
                full_response += content

        if hashing_kv is not None:
            await hashing_kv.upsert(
                {args_hash: {"return": full_response, "model": model}}
            )
        return full_response

    response = await openai_async_client.chat.completions.create(
        model=model, messages=messages, **kwargs
    )

    if hashing_kv is not None:
        await hashing_kv.upsert(
            {args_hash: {"return": response.choices[0].message.content, "model": model}}
        )
    return response.choices[0].message.content

```

**Comment by RoacherM** [comment]
> 我也遇到了ConnectionERROR的问题，且也用了vllm-server部署的Llama3.1。但是我本地没有开VPN，请问stream设置为true应该在哪里设置？我的代码：
> 
> ```
> import re
> import os
> import json
> import sys
> import asyncio
> from lightrag import LightRAG, QueryParam
> from lightrag.llm import openai_complete_if_cache, openai_embedding
> from lightrag.utils import EmbeddingFunc
> from lightrag.llm import hf_model_complete, hf_embedding
> import numpy as np
> import nest_asyncio
> from lightrag.llm import gpt_4o_mini_complete, gpt_4o_complete
> from openai import OpenAI
> import openai
> from transformers import AutoModel, AutoTokenizer
> 
> import logging
> 
> logger = logging.getLogger(__name__)
> logging.basicConfig(level=logging.INFO)
> 
> 
> local_api_base="http://localhost:8000/v1"
> local_api_key="EMPTY"
> local_model="/home/LLM_weights/meta-llama/Meta-Llama-3.1-70B-Instruct/"
> 
> client = OpenAI(api_key=OPEN_API_KEY_LIGHTRAG , base_url="https://api.agicto.cn/v1")
> 
> WORKING_DIR = "./dickens_all1118"
> 
> if not os.path.exists(WORKING_DIR):
>     os.mkdir(WORKING_DIR)
> 
> async def llm_model_func(
>     prompt, system_prompt=None, history_messages=[], **kwargs
> ) -> str:
>     return  await openai_complete_if_cache(
>         local_model,
>         prompt,
>         system_prompt=system_prompt,
>         history_messages=history_messages,
>         api_key=local_api_key,
>         base_url=local_api_base,
>         #stream=True,
>         **kwargs,
>     )
> 
> 
> async def embedding_func(texts: list[str]) -> np.ndarray:
>     return  await openai_embedding(
>         texts,
>         model="text-embedding-3-small",
>         api_key=OPEN_API_KEY_LIGHTRAG,
>         base_url=base_url_lightrag,
>     )
> 
> 
> async def get_embedding_dim():
>     test_text = ["This is a test sentence."]
>     embedding =  await embedding_func(test_text)
>     embedding_dim = embedding.shape[1]
>     return embedding_dim
> 
> 
> async def test_funcs():
>     result =  await llm_model_func("How are you?")
>     print("llm_model_func: ", result)
> 
>     result =  await embedding_func(["How are you?"])
>     print("embedding_func: ", result)
> 
> async def get_kg_lightrag():
>     try:
>         embedding_dimension =  await get_embedding_dim()
> 
>         rag = LightRAG(
>             working_dir=WORKING_DIR,
>             llm_model_func=llm_model_func,
>             embedding_func=EmbeddingFunc(
>                 embedding_dim=embedding_dimension, max_token_size=8192, func=embedding_func
>             ),
>         ) 
> 
>         with open("/data/test.txt") as f:
>             rag.insert(f.read())
> 
>         print("OKOKOK")
>         
>         
>     except Exception as e:
>         print(f"An error occurred: {e}")
> 
> 
> nest_asyncio.apply()
>         
> cvss_lightrag=asyncio.run(get_kg_lightrag())
>         
> os._exit(0)
> ```

修改llm.py中的函数，仅供参考。
```
@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=4, max=10),
    retry=retry_if_exception_type((RateLimitError, APIConnectionError, Timeout)),
)
async def openai_complete_if_cache(
    model,
    prompt,
    system_prompt=None,
    history_messages=[],
    stream=False,
    base_url=None,
    api_key=None,
    **kwargs,
) -> str:
    if api_key:
        os.environ["OPENAI_API_KEY"] = api_key

    openai_async_client = (
        AsyncOpenAI() if base_url is None else AsyncOpenAI(base_url=base_url)
    )
    hashing_kv: BaseKVStorage = kwargs.pop("hashing_kv", None)
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})
    if hashing_kv is not None:
        args_hash = compute_args_hash(model, messages)
        if_cache_return = await hashing_kv.get_by_id(args_hash)
        if if_cache_return is not None:
            return if_cache_return["return"]

    if stream:
        # 初始化response
        full_response = ""
        response = await openai_async_client.chat.completions.create(
            model=model, messages=messages, stream=stream, **kwargs
        )

        async for chunk in response:
            content = chunk.choices[0].delta.content
            if content:
                full_response += content

        if hashing_kv is not None:
            await hashing_kv.upsert(
                {args_hash: {"return": full_response, "model": model}}
            )
        return full_response

    response = await openai_async_client.chat.completions.create(
        model=model, messages=messages, **kwargs
    )

    if hashing_kv is not None:
        await hashing_kv.upsert(
            {args_hash: {"return": response.choices[0].message.content, "model": model}}
        )
    return response.choices[0].message.content
```

**Comment by zel2023** [comment]
感谢您的回复，我试试
