### ISSUE TITLE
No module named 'lightrag'

### ISSUE THREAD

**Issue by chenboju** [HKUDS/LightRAG#330]
Traceback (most recent call last):
  File "c:\Users\chen\Desktop\GitHub\Light\LightRAG\examples\lightrag_ollama_demo.py", line 3, in <module>
    from lightrag import LightRAG, QueryParam
ModuleNotFoundError: No module named 'lightrag'

**Comment by aaqib-ahmed-nazir** [comment]
#### Fix 1(recommend): 
- clone the repo first by:
```bash 
git clone https://github.com/HKUDS/LightRAG.git
```
- Then install it:
```bash 
cd LightRAG
pip install -e .
```
#### Fix2(`PyPi`):
```bash
pip install lightrag-hku
```

Will work :)

**Comment by chenboju** [comment]
謝謝，以上都試過了，不是那些問題造成。
但我已找到問題謝謝。
Thank you, I have tried all the above and it is not caused by those problems.
 But I have found the problem thanks.

**Comment by aaqib-ahmed-nazir** [comment]
You're welcome, also if you fixed it can you let me know the solution too?
Thanks

**Comment by chenboju** [comment]
Sorry, I made a newbie mistake
I used vs code to execute, which resulted in an error
![image](https://github.com/user-attachments/assets/3b3e3616-834b-4296-914d-b6babde72421)

The correct way is to use the terminal
python lightrag_ollama_demo.py

**Comment by aaqib-ahmed-nazir** [comment]
Ok yes, good that it works now

**Comment by chenboju** [comment]
Did you install it in Conda?
Make sure the paths are correct.
Python requires 11 or above

**Comment by zhuamaaa** [comment]
I met this problem too and still dont know how to solve:
(LightRAG_env) PS D:\LightRAG> python examples/lightrag_ollama_demo.py
Traceback (most recent call last):
  File "D:\LightRAG\examples\lightrag_ollama_demo.py", line 5, in <module>
    from lightrag import LightRAG, QueryParam
ModuleNotFoundError: No module named 'lightrag'

I have tried using FIX1 and excuting it in the terminal

**Comment by kwala007** [comment]
I am also having the same issue as the previous commenter. I installed from source in a virtual environment and I can see all the installed packages with pip freeze. However, importing lightrag fails with the error "No module named 'lightrag'." I've also tried executing this in both vscode terminal and regular command prompt. Is there a working fix for this?

![Image](https://github.com/user-attachments/assets/95e86108-e534-4302-842b-b6a3071eb889)
![Image](https://github.com/user-attachments/assets/875673ff-2cf1-42fc-ab59-574e10262550)

**Comment by ALW852** [comment]
Same, no matter directly execute in VS code or in terminal, both report No module named 'lightrag'

**Comment by xxrsdax** [comment]
有哪位大佬，明确问题并解决了吗

**Comment by xxrsdax** [comment]
改为 pip install lightrag-hku后，换了一个错误，No module named 'pandas'

**Comment by ImaginePilot** [comment]
解决方法：使用git clone而不是直接pip安装。版本问题。
