### ISSUE TITLE
ValueError bug

### ISSUE THREAD

**Issue by hxt365** [HKUDS/LightRAG#35]
```
Traceback (most recent call last):
  File "/export/scratch/scrapy/LightRAG/x.py", line 62, in <module>
    print(rag.query("What are the top themes in this story?", param=QueryParam(mode="naive")))
  File "/export/scratch/scrapy/LightRAG/lightrag/lightrag.py", line 248, in query
    return loop.run_until_complete(self.aquery(query, param))
  File "/home/miniconda3/envs/py3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/export/scratch/scrapy/LightRAG/lightrag/lightrag.py", line 282, in aquery
    response = await naive_query(
  File "/export/scratch/scrapy/LightRAG/lightrag/operate.py", line 975, in naive_query
    results = await chunks_vdb.query(query, top_k=query_param.top_k)
  File "/export/scratch/scrapy/LightRAG/lightrag/storage.py", line 108, in query
    results = self._client.query(
  File "/home/miniconda3/envs/py3.10/lib/python3.10/site-packages/nano_vectordb/dbs.py", line 147, in query
    return self.usable_metrics[self.metric](query, top_k, better_than_threshold)
  File "/home/miniconda3/envs/py3.10/lib/python3.10/site-packages/nano_vectordb/dbs.py", line 162, in _cosine_query
    scores = np.dot(use_matrix, query)
ValueError: shapes (42,1536) and (768,) not aligned: 1536 (dim 1) != 768 (dim 0)

**Comment by LarFii** [comment]
Thanks for your attention! This issue is most likely caused by the inconsistency between the embedding models used for insertion and querying.

**Comment by hxt365** [comment]
Thanks. I figured it out. I think the error message can be improved
