### ISSUE TITLE
examples\lightrag_ollama_demo.py  error :Could not automatically map gpt-4o-mini to a tokeniser

### ISSUE THREAD

**Issue by qidasheng** [HKUDS/LightRAG#365]
python lightrag_ollama_demo.py
INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:lightrag:Logger initialized for working directory: ./dickens
INFO:lightrag:Load KV llm_response_cache with 0 data
INFO:lightrag:Load KV full_docs with 0 data
INFO:lightrag:Load KV text_chunks with 0 data
INFO:lightrag:Loaded graph from ./dickens\graph_chunk_entity_relation.graphml with 0 nodes, 0 edges
INFO:nano-vectordb:Load (0, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens\\vdb_entities.json'} 0 data
INFO:nano-vectordb:Load (0, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens\\vdb_relationships.json'} 0 data
INFO:nano-vectordb:Load (0, 768) data
INFO:nano-vectordb:Init {'embedding_dim': 768, 'metric': 'cosine', 'storage_file': './dickens\\vdb_chunks.json'} 0 data
INFO:lightrag:[New Docs] inserting 1 docs
Chunking documents:   0%|                                                                          | 0/1 [00:00<?, ?doc/s]
INFO:lightrag:Writing graph with 0 nodes, 0 edges
Traceback (most recent call last):
  File "E:\data1\project\software\LightRAG\examples\lightrag_ollama_demo.py", line 31, in <module>
    rag.insert(f.read())
  File "e:\data1\project\software\lightrag\lightrag\lightrag.py", line 225, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
  File "D:\ProgramData\miniconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "e:\data1\project\software\lightrag\lightrag\lightrag.py", line 254, in ainsert
    for dp in chunking_by_token_size(
  File "e:\data1\project\software\lightrag\lightrag\operate.py", line 35, in chunking_by_token_size
    tokens = encode_string_by_tiktoken(content, model_name=tiktoken_model)
  File "e:\data1\project\software\lightrag\lightrag\utils.py", line 140, in encode_string_by_tiktoken
    ENCODER = tiktoken.encoding_for_model(model_name)
  File "C:\Users\qsfzz\AppData\Roaming\Python\Python310\site-packages\tiktoken\model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "C:\Users\qsfzz\AppData\Roaming\Python\Python310\site-packages\tiktoken\model.py", line 84, in encoding_name_for_model
    raise KeyError(
KeyError: 'Could not automatically map gpt-4o-mini to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'

**Comment by GreenerZ** [comment]
upgrade tiktoken
