### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'global_config'

### ISSUE THREAD

**Issue by alllexx88** [HKUDS/LightRAG#466]
When trying to use `LightRAG` init arg `enable_llm_cache=False`, I get this error during `rag.insert`:

```
Traceback (most recent call last):
  File "/home/alex/src/LightRAG/enable_llm_cache_test.py", line 30, in <module>
    rag.insert(f.read())
  File "/home/alex/src/LightRAG/lightrag/lightrag.py", line 283, in insert
    return loop.run_until_complete(self.ainsert(string_or_strings))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/.pixi/envs/default/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/lightrag/lightrag.py", line 334, in ainsert
    maybe_new_kg = await extract_entities(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/lightrag/operate.py", line 377, in extract_entities
    results.append(await result)
                   ^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/.pixi/envs/default/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/alex/src/LightRAG/lightrag/operate.py", line 311, in _process_single_content
    final_result = await use_llm_func(hint_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/lightrag/utils.py", line 127, in wait_func
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/src/LightRAG/lightrag/llm.py", line 590, in ollama_model_complete
    model_name = kwargs["hashing_kv"].global_config["llm_model_name"]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'global_config'
```

This is the code I'm trying to run:
```python
import os

from lightrag import LightRAG, QueryParam
from lightrag.llm import ollama_embedding, ollama_model_complete
from lightrag.utils import EmbeddingFunc

WORKING_DIR = "./dickens"

if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)

rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=ollama_model_complete,
    llm_model_name="llama3.1:8b",
    llm_model_max_async=4,
    llm_model_max_token_size=32768,
    llm_model_kwargs={"host": "http://localhost:11434", "options": {"num_ctx": 32768}},
    embedding_func=EmbeddingFunc(
        embedding_dim=768,
        max_token_size=8192,
        func=lambda texts: ollama_embedding(
            texts, embed_model="nomic-embed-text", host="http://localhost:11434"
        ),
    ),
    enable_llm_cache=False,
)

with open("./book.txt", "r", encoding="utf-8") as f:
    rag.insert(f.read())

print(rag.query("What are Scrooge's greatest fears?", param=QueryParam(mode="hybrid")))
```

**Comment by theClassLight** [comment]
enable_llm_cache=False causes error when rag.query() work
