### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by fireSunset** [HKUDS/LightRAG#472]
Before the use of HF model, has been able to run successfully, these days no matter using HF model or zhipuai will be the same error, re-install the environment and the project is still the same error!Why would it end up continuing to choose the openai model causing the connection to fail? 😭
![8ff1c93d-a17e-4740-b247-183f00d73c15](https://github.com/user-attachments/assets/f51de9eb-7030-4caf-8b93-f57bdb731442)

**Comment by fireSunset** [comment]
![291abec3-be86-46e8-be1f-219c043d5104](https://github.com/user-attachments/assets/b49df1fd-a36f-4fed-bcb7-d39223e38179)
What's even stranger is that using the official book.txt doesn't extract any knowledge

**Comment by fireSunset** [comment]
Obviously the model has been replaced, but it always looks for openai:
Traceback (most recent call last):
  File "/home/lww/.conda/envs/LightRAG3/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/lww/.conda/envs/LightRAG3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "/home/lww/.conda/envs/LightRAG3/lib/python3.9/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/o200k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f13e03ee820>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by kyre-99** [comment]
I have the same problem as you, can you please solve it?

**Comment by kyre-99** [comment]
> I have the same problem as you, can you please solve it?我和你有同样的问题，请问你能解决吗？

i have solved this，it needs vpn ，damn

**Comment by hermitly** [comment]
This blog can solve the problem：https://blog.csdn.net/yufanwenshu/article/details/142290067
