### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\dickens\\lightrag.log'

### ISSUE THREAD

**Issue by brunoedcf** [HKUDS/LightRAG#53]
When I create the LightRAG, it keeps looking for the dickens\\lightrag.log file even though I set the WORKING_DIR to be the correct file where the lightrag,log is.

Error:

Traceback (most recent call last):
  File "C:\Users\bruno\Documents\DESENVOLVIMENTO\normativos-light-rag\main.py", line 3, in <module>
    from src.rag_flow.document_rag import rag_documents
  File "C:\Users\bruno\Documents\DESENVOLVIMENTO\normativos-light-rag\src\rag_flow\__init__.py", line 95, in <module>
    rag = LightRAG(
  File "<string>", line 25, in __init__
  File "C:\Users\bruno\Documents\DESENVOLVIMENTO\normativos-light-rag\venv\lib\site-packages\lightrag\lightrag.py", line 103, in __post_init__
    set_logger(log_file)
  File "C:\Users\bruno\Documents\DESENVOLVIMENTO\normativos-light-rag\venv\lib\site-packages\lightrag\utils.py", line 22, in set_logger
    file_handler = logging.FileHandler(log_file)
  File "C:\Users\bruno\.pyenv\pyenv-win\versions\3.10.11\lib\logging\__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\bruno\.pyenv\pyenv-win\versions\3.10.11\lib\logging\__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bruno\\Documents\\DESENVOLVIMENTO\\normativos-light-rag\\dickens\\lightrag.log'

Code: 

```
import os
import numpy as np
import aiohttp
import logging
from lightrag import LightRAG, QueryParam
from lightrag.utils import EmbeddingFunc
from dotenv import load_dotenv

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler()]
)

load_dotenv()


AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")

AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_EMBEDDING_API_VERSION = os.getenv("AZURE_EMBEDDING_API_VERSION")


async def llm_model_func(
    prompt, system_prompt=None, history_messages=[], **kwargs
) -> str:
    headers = {
        "Content-Type": "application/json",
        "api-key": AZURE_OPENAI_API_KEY,
    }
    endpoint = f"{AZURE_OPENAI_ENDPOINT}openai/deployments/{AZURE_OPENAI_DEPLOYMENT}/chat/completions?api-version={AZURE_OPENAI_API_VERSION}"

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    if history_messages:
        messages.extend(history_messages)
    messages.append({"role": "user", "content": prompt})

    payload = {
        "messages": messages,
        "temperature": kwargs.get("temperature", 0),
        "top_p": kwargs.get("top_p", 1),
        "n": kwargs.get("n", 1),
    }

    async with aiohttp.ClientSession() as session:
        async with session.post(endpoint, headers=headers, json=payload) as response:
            if response.status != 200:
                raise ValueError(
                    f"Request failed with status {response.status}: {await response.text()}"
                )
            result = await response.json()
            return result["choices"][0]["message"]["content"]


async def embedding_func(texts: list[str]) -> np.ndarray:
    headers = {
        "Content-Type": "application/json",
        "api-key": AZURE_OPENAI_API_KEY,
    }
    endpoint = f"{AZURE_OPENAI_ENDPOINT}openai/deployments/{AZURE_EMBEDDING_DEPLOYMENT}/embeddings?api-version={AZURE_EMBEDDING_API_VERSION}"

    payload = {"input": texts}

    async with aiohttp.ClientSession() as session:
        async with session.post(endpoint, headers=headers, json=payload) as response:
            if response.status != 200:
                raise ValueError(
                    f"Request failed with status {response.status}: {await response.text()}"
                )
            result = await response.json()
            embeddings = [item["embedding"] for item in result["data"]]
            return np.array(embeddings)


def rag_documents():
    base_dir = os.path.abspath(os.path.join(
        os.path.dirname(__file__), "../../"))
    WORKING_DIR = os.path.join(base_dir, "assets", "knowledge_working_dir")

    embedding_dimension = 3072
    rag = LightRAG(
        working_dir=WORKING_DIR,
        llm_model_func=llm_model_func,
        embedding_func=EmbeddingFunc(
            embedding_dim=embedding_dimension,
            max_token_size=8192,
            func=embedding_func,
        ),
    )

    query_text = ""
    while (query_text != "quit"):
        query_text = input("Qual a sua pergunta?")
        print("\n\n\nResultado (Hybrid):\n\n\n")
        print(rag.query(query_text, param=QueryParam(mode="hybrid")))
        print("\n\n\n")

```

**Comment by LarFii** [comment]
The issue is caused by the working directory not existing. You can automatically create the working directory using the following code:
```python
if not os.path.exists(WORKING_DIR):
    os.mkdir(WORKING_DIR)
```
