### ISSUE TITLE
UnicodeDecodeError when running the example script provided

### ISSUE THREAD

**Issue by venki-lfc** [HKUDS/LightRAG#81]
I tried to run the example script provided in the README with dickens/book.txt. When I run the script I face this error. I read in other issue to change the encoding to utf-8 in the  dbs.py file of nano-vector db but it is not working for me. I get this error:
```
  File "C:\Users\Venkatesan.KALAPATTI\Projects\LightRAG\test.py", line 26, in <module>
    rag.insert(f.read())
  File "C:\Users\Venkatesan.KALAPATTI\AppData\Local\miniconda3\envs\lightrag\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 171917: character maps to <undefined>
```
![image](https://github.com/user-attachments/assets/3918db71-ca01-4228-b335-724ca55b8ad3)

**Comment by daviddwlee84** [comment]
I got a similar error when constructing `LightRAG` with [https://r.jina.ai/https://arxiv.org/html/2410.05779](https://r.jina.ai/https://arxiv.org/html/2410.05779)

```
Traceback (most recent call last):
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\david\Documents\Program\Streamlit_OpenAI_ChatTemplate\pages\5_Retrieval_Augmentation_(LightRAG).py", line 53, in <module>
    rag = LightRAG(
          ^^^^^^^^^
  File "<string>", line 25, in __init__
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\lightrag\lightrag.py", line 138, in __post_init__
    self.entities_vdb = self.vector_db_storage_cls(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 8, in __init__
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\lightrag\storage.py", line 68, in __post_init__
    self._client = NanoVectorDB(
                   ^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\nano_vectordb\dbs.py", line 69, in __post_init__
    storage: DataBase = load_storage(self.storage_file) or default_storage
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\nano_vectordb\dbs.py", line 37, in load_storage
    data = json.load(f)
           ^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 19799: character maps to <undefined>
```

---

And found to be caused by the Nano VectorDB package

https://github.com/gusye1234/nano-vectordb/blob/bbd27c39264ef130079bd2b71690ad966f3eae36/nano_vectordb/dbs.py#L33-L37

https://github.com/HKUDS/LightRAG/issues/37#issuecomment-2420410149

**Comment by LMcontent** [comment]
replace the line `with open("./book.txt") as f:` with this one `with open("./book.txt",encoding="UTF-8") as f:`

**Comment by venki-lfc** [comment]
Solved the issue, thank you :)
