### ISSUE TITLE
local查询总是报json.decoder.JSONDecodeError错误

### ISSUE THREAD

**Issue by blueskydata** [HKUDS/LightRAG#99]
以下为代码：
rag = LightRAG(
    working_dir=WORKING_DIR,
    llm_model_func=ollama_model_complete,
    llm_model_name="llama3.1:8b2m",
    embedding_func=EmbeddingFunc(
        embedding_dim=768,
        max_token_size=8192,
        func=lambda texts: ollama_embedding(texts, embed_model="nomic-embed-text"),
    ),
)
while True:
    que = input('>')
    if len(que) == 0:
        break
    result = rag.query(que, param=QueryParam(mode="local"))
    print(result)
    print('-----------------------------------------------------------------------------------')
print('bye bye')

以下为日志：
INFO:lightrag:Creating a new event loop in a sub-thread.
INFO:httpx:HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/home/***/prj/LightRAG/lightrag/operate.py", line 407, in local_query
    keywords_data = json.loads(result)
                    ^^^^^^^^^^^^^^^^^^
  File "/prj/anaconda3/envs/llm/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prj/anaconda3/envs/llm/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prj/anaconda3/envs/llm/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/prj/LightRAG/examples/ollama_jzm.py", line 55, in <module>
    result = rag.query(que, param=QueryParam(mode="local"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/prj/LightRAG/lightrag/lightrag.py", line 244, in query
    return loop.run_until_complete(self.aquery(query, param))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/prj/anaconda3/envs/llm/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/***/prj/LightRAG/lightrag/lightrag.py", line 248, in aquery
    response = await local_query(
               ^^^^^^^^^^^^^^^^^^
  File "/home/***/prj/LightRAG/lightrag/operate.py", line 418, in local_query
    result = "{" + result.split("{")[1].split("}")[0] + "}"
                   ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

请问如何解决，谢谢！！！

**Comment by LarFii** [comment]
llama在我们的测试中也经常不按json格式返回，换qwen2.5会好一点
